language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
before_install:
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then bash ./CI/travis.linux.before_install.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/travis.osx.before_install.sh; fi
  #- ./CI/travis.linux.before_install.sh
install:
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then bash ./CI/travis.linux.install.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/travis.osx.install.sh; fi
  #- ./CI/travis.linux.install.sh
before_script:
  - mkdir build
  - cd src
script:
  - qmake && make -j2
  - cd ../build
  - cmake ..
  - make -j2
matrix:
  allow_failures:
    - os: osx
