language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
before_install: ./CI/travis.before_install.sh
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then bash ./CI/travis.linux.before_install.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/travis.osx.before_install.sh; fi
  #- ./CI/travis.linux.before_install.sh
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then bash ./CI/travis.linux.install.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/travis.osx.install.sh; fi
  #- ./CI/travis.linux.install.sh
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi
  - mkdir build
  - cd src
script:
  - qmake && make -j2
  - cd ../build
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake .. && make -j2; fi
notifications:
matrix:
  allow_failures:
    - os: osx
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
